const EXAM_KIND="writing";
const EXAM_DEMO_FIXTURES={"sample-writing-mail-2026": {"directions": "51. Writing · Part A", "stem": {"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Read the following email from your friend Paul and write him a reply."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Hi Li Ming,"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "I was really moved by the Chinese families’ handwritten letters you posted yesterday. They are priceless! Could you please tell me a bit more about them? And are they currently on pubic display somewhere? I’m very keen to see them in person. Thanks."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Yours,"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Paul"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "You should write about 100 words on the ANSWER SHEET."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Do not use your own name in your email; use “Li Ming” instead. (10 points)"}]}]}, "referenceAnswer": "", "rubric": "", "maxScore": 10}, "sample-writing-chart-2026": {"directions": "52. Writing · Part B", "stem": {"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Write an essay based on the charts below. In your essay, you should"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "1) describe the charts briefly,"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "2) interpret the charts, and"}]}, {"type": "paragraph", "content": [{"type": "text", "text": "3) give your comments."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Write your answer in 160–200 words on the ANSWER SHEET. (20 points)"}]}, {"type": "image", "attrs": {"assetId": "770758340583c5b9e7837deedfa503e9e3e81c57c6f6a7c74736ddf29bbd689f", "alt": "养老机器人消费者接受度与首要关注点调查原图", "width": 620, "align": "center"}}]}, "referenceAnswer": "", "rubric": "", "maxScore": 20}};
(() => {
  const root=document.getElementById('exam-editor');
  let original=null,draft=null,baseline='',activeEditor=null,disposed=false;
  const targets=new Map(),renderers=[];
  const clone=value=>JSON.parse(JSON.stringify(value));
  const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
  function grow(input){input.style.height='auto';input.style.height=Math.max(24,input.scrollHeight)+'px';}
  function textField(parent,label,value,onChange){const box=el('div','editor-field');const id='edit-'+Math.random().toString(36).slice(2,9);const caption=el('label',null,label);caption.htmlFor=id;const input=el('textarea','editor-input');input.id=id;input.rows=1;input.value=value||'';input.addEventListener('input',()=>{onChange(input.value);grow(input);});box.append(caption,input);parent.append(box);return input;}
  function score(parent,item){const box=el('label','score-editor','满分');const input=el('input');input.type='text';input.inputMode='decimal';input.value=item.maxScore;input.setAttribute('aria-label','满分');input.addEventListener('input',()=>{item.maxScore=input.value;});box.append(input,el('span',null,'分'));parent.append(box);}
  const icon=locked=>locked?'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 7.6-1.8"/></svg>';
  function alerts(message=''){let n=root.querySelector('.editor-alert');if(!n){n=el('p','editor-alert');n.setAttribute('role','alert');root.append(n);}n.textContent=message;n.hidden=!message;}
  function lockCheck(){const count=draft.sequence.filter(s=>s.fixed).length;const n=root.querySelector('.lock-count');n.textContent=`已固定 ${count} 个 · 至少固定 3 个`;n.classList.toggle('invalid',count<3);alerts(count<3?'至少固定三个选项后才能保存。':'');return count>=3;}
  function orderEditor(parent){
    const seq=el('section','editor-field');seq.append(el('h2','section-title','顺序与固定选项'));const grid=el('div','editor-lock-sequence');
    draft.sequence.forEach((slot,index)=>{const box=el('div','edit-order-slot'+(slot.fixed?' locked':''));box.id=slot.id;box.tabIndex=-1;targets.set(slot.id,box);const select=el('select');select.setAttribute('aria-label',`位置 ${index+1} 的段落`);for(const paragraph of draft.paragraphs)select.append(new Option(paragraph.id,paragraph.id));select.value=slot.paragraphId;select.addEventListener('change',()=>{slot.paragraphId=select.value;});const lock=el('button','lock-button');lock.type='button';lock.innerHTML=icon(slot.fixed);lock.setAttribute('aria-label',`${slot.fixed?'解锁':'固定'}位置 ${index+1}`);lock.setAttribute('aria-pressed',String(slot.fixed));lock.addEventListener('click',()=>{slot.fixed=!slot.fixed;lock.innerHTML=icon(slot.fixed);lock.setAttribute('aria-label',`${slot.fixed?'解锁':'固定'}位置 ${index+1}`);lock.setAttribute('aria-pressed',String(slot.fixed));box.classList.toggle('locked',slot.fixed);lockCheck();});box.append(select,lock);grid.append(box);});seq.append(grid,el('p','lock-count'));parent.append(seq);
    for(const p of draft.paragraphs)textField(parent,p.id+' · 段落',p.text,value=>p.text=value);
    textField(parent,'解析',draft.explanation,value=>draft.explanation=value);score(parent,draft);lockCheck();
  }
  function partsEditor(parent){
    for(const p of draft.parts){const section=el('section','editor-part');section.id=p.id;section.tabIndex=-1;targets.set(p.id,section);section.append(el('h2',null,p.label+'.'));
      if(EXAM_KIND==='reading')textField(section,'小题题干',p.stem,value=>p.stem=value);
      if(p.options){const options=el('div');for(const option of p.options){const row=el('div','editor-choice'+(option.id===p.correctOptionId?' is-key':''));const key=el('button',null,option.id);key.type='button';key.setAttribute('aria-label',`将 ${p.label} 题正确答案设为 ${option.id}`);key.setAttribute('aria-pressed',String(option.id===p.correctOptionId));key.addEventListener('click',()=>{p.correctOptionId=option.id;options.querySelectorAll('.editor-choice').forEach(n=>{const selected=n===row;n.classList.toggle('is-key',selected);n.querySelector('button').setAttribute('aria-pressed',String(selected));});});const input=el('textarea');input.rows=1;input.value=option.text;input.setAttribute('aria-label',`${p.label} 题选项 ${option.id}`);input.addEventListener('input',()=>{option.text=input.value;grow(input);});row.append(key,input);options.append(row);}section.append(options);textField(section,'解析',p.explanation,value=>p.explanation=value);}
      else {textField(section,'翻译原句',p.stem,value=>p.stem=value);textField(section,'参考译文',p.referenceAnswer,value=>p.referenceAnswer=value);textField(section,'评分说明',p.rubric,value=>p.rubric=value);}
      score(section,p);parent.append(section);
    }
    if(EXAM_KIND==='translation')score(parent,draft);
  }
  async function flush(){if(activeEditor){await activeEditor.flush();draft.stem=activeEditor.getDocument();}}
  function disposeRich(){if(activeEditor){activeEditor.destroy();activeEditor=null;}for(const r of renderers.splice(0))r.destroy();}
  async function render(){disposeRich();targets.clear();root.replaceChildren();const source=el('section','editor-field');source.append(el('h2','section-title','题干'));const host=el('div');source.append(host);root.append(source);
    activeEditor=QF.content.createEditor(host,{doc:clone(draft.stem),onChange(value){draft.stem=value;},placeholder:'题干内容'});await activeEditor.ready;if(disposed)return;
    if(EXAM_KIND==='paragraph-order')orderEditor(root);else if(draft.parts)partsEditor(root);else {textField(root,'参考范文',draft.referenceAnswer,value=>draft.referenceAnswer=value);textField(root,'评分说明',draft.rubric,value=>draft.rubric=value);score(root,draft);}
    root.append(el('p','notice','空白内容可在以后补充。当前为界面演示，修改尚未写入题库。'));root.querySelectorAll('textarea').forEach(grow);QF.ui.resize();
  }
  function normalize(){const value=clone(draft);value.maxScore=Number(value.maxScore);for(const p of value.parts||[])p.maxScore=Number(p.maxScore);return value;}
  async function documentValue(){if(!window.EXAM_STANDALONE_DEMO){const error=new Error("DEVELOPMENT_NOT_IMPLEMENTED: 当前为 UI 原型，题目保存尚未实现；编辑输入已保留。");error.code="DEVELOPMENT_NOT_IMPLEMENTED";throw error;}await flush();if(EXAM_KIND==='paragraph-order'){
      if(!lockCheck())throw new Error('至少固定三个选项后才能保存。');const ids=draft.sequence.map(s=>s.paragraphId);if(new Set(ids).size!==draft.paragraphs.length){alerts('每个段落应在顺序中恰好出现一次。');throw new Error('排序中的段落不能重复或遗漏。');}}
    const value=normalize();if(!Number.isFinite(value.maxScore)||value.maxScore<=0||(value.parts||[]).some(p=>!Number.isFinite(p.maxScore)||p.maxScore<=0)){alerts('分值必须为正数。');throw new Error('分值必须为正数。');}
    alerts('');return {title:original.title,data:value};
  }
  QF.editor.register({async onLoad(context){original=clone(context.question);draft=clone(original.data);baseline=JSON.stringify(draft);await render();},getDocument:documentValue,hasChanges(){return JSON.stringify(draft)!==baseline;},async exportDraft(){await flush();return clone(draft);},async importDraft(value){draft=clone(value);await render();},onFlush:flush,async onOutlineNavigate(id){await flush();const target=targets.get(id);if(!target)return false;target.scrollIntoView({block:'center'});target.focus({preventScroll:true});return true;},onDispose(){disposed=true;disposeRich();targets.clear();}}).catch(error=>alerts(error.message));
})();
